general:
  repo_root: "."  # Root of Barbados-Historic-Handwriting-Challenge

training:
  model_id: "Qwen/Qwen2-VL-2B-Instruct"
  train_csv: "Train_Cleaned.csv"
  base_image_dir: "data/processed_images"
  output_dir: "./qwen2-vl-ocr"
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 4
  num_train_epochs: 8
  learning_rate: 0.00005
  dataloader_num_workers: 4
  max_pixels: 1500000
  use_bf16: true
  debug: false
  r: 32
  lora_alpha: 64

inference:
  model_path: "./qwen2-vl-ocr/final"
  test_csv: "Test.csv"
  base_image_dir: "data/processed_images"
  output_csv: "submission_vlm.csv"
  device: "auto"
  use_bf16: false
  max_new_tokens: 128
  num_beams: 1

evaluation:
  pred_csv: "submission_vlm.csv"
  pub_gt: "data/train_folds.csv"
  weight_factor: 0.5