import os
import json

notebook_content = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# R.O.A.D. Barbados Historic Handwriting Challenge\n",
    "## Complete PyTorch CRNN Training & Evaluation Pipeline for AWS SageMaker (`ml.g4dn.2xlarge`)\n",
    "\n",
    "This notebook trains a **Convolutional Recurrent Neural Network (CRNN)** to convergence on the preprocessed Barbados Historic Handwriting dataset.\n",
    "\n",
    "### Pipeline Overview:\n",
    "1. **GPU & CUDA Environment Verification** (`NVIDIA T4` / `A10G` GPU)\n",
    "2. **Preprocessed Image & Fold Auto-Verification** (`data/processed_images/` & `data/train_folds.csv`)\n",
    "3. **PyTorch Dataset with Handwriting Data Augmentations** (RandomRotation, ColorJitter, ImageNet normalization)\n",
    "4. **CRNN Architecture** (ResNet-18 4x width downsampling backbone + 2-layer BiLSTM + CTC Head)\n",
    "5. **Mixed Precision Training (`torch.cuda.amp`) & CosineAnnealingLR Scheduler**\n",
    "6. **Official Zindi Metric Evaluation** ($0.5 \\times \\text{Weighted CER} + 0.5 \\times \\text{Weighted WER}$)\n",
    "7. **Test Set Inference & `submission.csv` Export**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 1: System & GPU Environment Verification\n",
    "import os\n",
    "import sys\n",
    "import time\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "from torch.utils.data import DataLoader\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# Ensure project root is in sys.path\n",
    "PROJECT_ROOT = os.path.abspath(\".\")\n",
    "if PROJECT_ROOT not in sys.path:\n",
    "    sys.path.insert(0, PROJECT_ROOT)\n",
    "\n",
    "from src.dataset import Tokenizer, BarbadosOCRDataset, OCRCollateFn\n",
    "from src.model import CRNN_OCR\n",
    "from src.metrics import compute_zindi_metric\n",
    "\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print(f\"✓ Execution Device       : {device}\")\n",
    "if torch.cuda.is_available():\n",
    "    print(f\"✓ GPU Device Name       : {torch.cuda.get_device_name(0)}\")\n",
    "    print(f\"✓ VRAM Memory Available : {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB\")\n",
    "else:\n",
    "    print(\"⚠️ Running on CPU mode. GPU instance (ml.g4dn.2xlarge) is recommended for fast convergence.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Image Preprocessing & Stratified Folds Auto-Verification"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 2: Auto-verify preprocessed images and folds\n",
    "proc_img_dir = os.path.join(PROJECT_ROOT, 'data', 'processed_images')\n",
    "os.makedirs(proc_img_dir, exist_ok=True)\n",
    "\n",
    "if len(os.listdir(proc_img_dir)) < 5000:\n",
    "    print(\"⚙️ Preprocessed images directory is empty or incomplete. Running batch image preprocessing (takes ~15s)...\")\n",
    "    from scratch.batch_process_all_images import main as batch_preprocess_main\n",
    "    batch_preprocess_main()\n",
    "\n",
    "train_folds_path = os.path.join(PROJECT_ROOT, 'data', 'train_folds.csv')\n",
    "if not os.path.exists(train_folds_path):\n",
    "    train_folds_path = os.path.join(PROJECT_ROOT, 'Train_Folds.csv')\n",
    "\n",
    "df_folds = pd.read_csv(train_folds_path)\n",
    "print(f\"✓ Preprocessed Images Ready : {len(os.listdir(proc_img_dir)):,} files in {proc_img_dir}\")\n",
    "print(f\"✓ Stratified Training Rows  : {len(df_folds):,} rows in {train_folds_path}\")\n",
    "print(\"✓ Per-Fold Sample Distribution:\")\n",
    "for fold_idx in range(5):\n",
    "    count = len(df_folds[df_folds['fold'] == fold_idx])\n",
    "    mean_len = df_folds[df_folds['fold'] == fold_idx]['text_length'].mean()\n",
    "    print(f\"   • Fold {fold_idx}: {count:,} samples | Mean Text Length: {mean_len:.2f} chars\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. GPU-Accelerated Training Engine (`train_fold`)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def train_epoch_gpu(\n",
    "    model: nn.Module,\n",
    "    dataloader: DataLoader,\n",
    "    optimizer: torch.optim.Optimizer,\n",
    "    criterion: nn.Module,\n",
    "    scaler: Optional[torch.cuda.amp.GradScaler],\n",
    "    device: torch.device\n",
    ") -> float:\n",
    "    model.train()\n",
    "    running_loss = 0.0\n",
    "    total_samples = 0\n",
    "\n",
    "    for batch in dataloader:\n",
    "        images = batch['images'].to(device)\n",
    "        targets = batch['targets'].to(device)\n",
    "        input_lengths = batch['input_lengths'].to(device)\n",
    "        target_lengths = batch['target_lengths'].to(device)\n",
    "\n",
    "        optimizer.zero_grad()\n",
    "\n",
    "        if scaler is not None and device.type == 'cuda':\n",
    "            with torch.cuda.amp.autocast():\n",
    "                logits = model(images)\n",
    "                log_probs = F.log_softmax(logits, dim=2).permute(1, 0, 2)\n",
    "                loss = criterion(log_probs, targets, input_lengths, target_lengths)\n",
    "            \n",
    "            if not (torch.isnan(loss) or torch.isinf(loss)):\n",
    "                scaler.scale(loss).backward()\n",
    "                scaler.unscale_(optimizer)\n",
    "                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=5.0)\n",
    "                scaler.step(optimizer)\n",
    "                scaler.update()\n",
    "        else:\n",
    "            logits = model(images)\n",
    "            log_probs = F.log_softmax(logits, dim=2).permute(1, 0, 2)\n",
    "            loss = criterion(log_probs, targets, input_lengths, target_lengths)\n",
    "            \n",
    "            if not (torch.isnan(loss) or torch.isinf(loss)):\n",
    "                loss.backward()\n",
    "                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=5.0)\n",
    "                optimizer.step()\n",
    "\n",
    "        if not (torch.isnan(loss) or torch.isinf(loss)):\n",
    "            batch_size = images.size(0)\n",
    "            running_loss += loss.item() * batch_size\n",
    "            total_samples += batch_size\n",
    "\n",
    "    return running_loss / max(1, total_samples)\n",
    "\n",
    "@torch.no_grad()\n",
    "def evaluate_epoch_gpu(\n",
    "    model: nn.Module,\n",
    "    dataloader: DataLoader,\n",
    "    tokenizer: Tokenizer,\n",
    "    device: torch.device\n",
    ") -> dict:\n",
    "    model.eval()\n",
    "    all_preds = []\n",
    "    all_refs = []\n",
    "\n",
    "    for batch in dataloader:\n",
    "        images = batch['images'].to(device)\n",
    "        target_texts = batch['target_texts']\n",
    "\n",
    "        if device.type == 'cuda':\n",
    "            with torch.cuda.amp.autocast():\n",
    "                logits = model(images)\n",
    "        else:\n",
    "            logits = model(images)\n",
    "\n",
    "        preds = model.decode_greedy(logits, tokenizer)\n",
    "        all_preds.extend(preds)\n",
    "        all_refs.extend(target_texts)\n",
    "\n",
    "    return compute_zindi_metric(all_preds, all_refs, cer_weight=0.5, wer_weight=0.5)\n",
    "\n",
    "def train_crnn_fold(\n",
    "    fold: int = 0,\n",
    "    epochs: int = 25,\n",
    "    batch_size: int = 32,\n",
    "    learning_rate: float = 1e-3,\n",
    "    use_amp: bool = True\n",
    "):\n",
    "    print(f\"\\n==================================================\")\n",
    "    print(f\" TRAINING FOLD {fold} ({epochs} Epochs, Batch Size: {batch_size}, LR: {learning_rate})\")\n",
    "    print(f\"==================================================\")\n",
    "\n",
    "    df_train = df_folds[df_folds['fold'] != fold].reset_index(drop=True)\n",
    "    df_val = df_folds[df_folds['fold'] == fold].reset_index(drop=True)\n",
    "\n",
    "    img_dir = os.path.join(PROJECT_ROOT, 'data', 'processed_images')\n",
    "    tokenizer = Tokenizer()\n",
    "\n",
    "    train_dataset = BarbadosOCRDataset(df_train, img_dir=img_dir, tokenizer=tokenizer, is_train=True)\n",
    "    val_dataset = BarbadosOCRDataset(df_val, img_dir=img_dir, tokenizer=tokenizer, is_train=False)\n",
    "\n",
    "    collate_fn = OCRCollateFn(downsample_factor=4, pad_value=0.0)\n",
    "\n",
    "    num_workers = 4 if torch.cuda.is_available() else 0\n",
    "    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, collate_fn=collate_fn, num_workers=num_workers, pin_memory=torch.cuda.is_available())\n",
    "    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, collate_fn=collate_fn, num_workers=num_workers, pin_memory=torch.cuda.is_available())\n",
    "\n",
    "    model = CRNN_OCR(vocab_size=len(tokenizer), hidden_size=256, pretrained_backbone=True).to(device)\n",
    "    criterion = nn.CTCLoss(blank=tokenizer.blank_idx, zero_infinity=True).to(device)\n",
    "    optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=1e-4)\n",
    "    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs, eta_min=1e-5)\n",
    "    scaler = torch.cuda.amp.GradScaler() if (use_amp and device.type == 'cuda') else None\n",
    "\n",
    "    models_dir = os.path.join(PROJECT_ROOT, 'models')\n",
    "    os.makedirs(models_dir, exist_ok=True)\n",
    "    checkpoint_path = os.path.join(models_dir, f\"crnn_best_fold{fold}.pt\")\n",
    "\n",
    "    best_score = float('inf')\n",
    "    best_epoch = -1\n",
    "    history = {'train_loss': [], 'val_score': [], 'val_cer': [], 'val_wer': []}\n",
    "\n",
    "    start_time = time.time()\n",
    "    for epoch in range(1, epochs + 1):\n",
    "        ep_start = time.time()\n",
    "        t_loss = train_epoch_gpu(model, train_loader, optimizer, criterion, scaler, device)\n",
    "        scheduler.step()\n",
    "\n",
    "        v_res = evaluate_epoch_gpu(model, val_loader, tokenizer, device)\n",
    "        v_score, v_cer, v_wer = v_res['final_score'], v_res['weighted_cer'], v_res['weighted_wer']\n",
    "\n",
    "        history['train_loss'].append(t_loss)\n",
    "        history['val_score'].append(v_score)\n",
    "        history['val_cer'].append(v_cer)\n",
    "        history['val_wer'].append(v_wer)\n",
    "\n",
    "        is_best = v_score < best_score\n",
    "        if is_best:\n",
    "            best_score = v_score\n",
    "            best_epoch = epoch\n",
    "            torch.save({\n",
    "                'epoch': epoch,\n",
    "                'model_state_dict': model.state_dict(),\n",
    "                'val_score': v_score,\n",
    "                'val_cer': v_cer,\n",
    "                'val_wer': v_wer,\n",
    "                'vocab_size': len(tokenizer)\n",
    "            }, checkpoint_path)\n",
    "\n",
    "        mark = \"★ BEST\" if is_best else \"\"\n",
    "        print(f\"Epoch [{epoch:02d}/{epochs:02d}] ({time.time()-ep_start:.1f}s) | Loss: {t_loss:.4f} | Val Score: {v_score:.4f} (CER: {v_cer:.4f}, WER: {v_wer:.4f}) {mark}\")\n",
    "\n",
    "    print(f\"\\n✓ FOLD {fold} TRAINING COMPLETED ({time.time()-start_time:.1f}s). Best Val Score: {best_score:.4f} at Epoch {best_epoch}\")\n",
    "    return checkpoint_path, history"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Run Model Training (Fold 0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Execute Fold 0 Training\n",
    "best_checkpoint, history = train_crnn_fold(fold=0, epochs=25, batch_size=32, learning_rate=1e-3, use_amp=True)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Training Loss & Metric Curves"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "plt.figure(figsize=(14, 5), dpi=120)\n",
    "plt.subplot(1, 2, 1)\n",
    "plt.plot(history['train_loss'], label='Train CTC Loss', color='#00E5FF', linewidth=2)\n",
    "plt.title('Training CTC Loss Curve', fontsize=12, fontweight='bold')\n",
    "plt.xlabel('Epoch')\n",
    "plt.ylabel('CTC Loss')\n",
    "plt.grid(True, linestyle=':', alpha=0.5)\n",
    "plt.legend()\n",
    "\n",
    "plt.subplot(1, 2, 2)\n",
    "plt.plot(history['val_score'], label='Zindi Score (0.5 CER + 0.5 WER)', color='#FF5252', linewidth=2)\n",
    "plt.plot(history['val_cer'], label='Weighted CER', linestyle='--', color='#FFD700')\n",
    "plt.plot(history['val_wer'], label='Weighted WER', linestyle=':', color='#76FF03')\n",
    "plt.title('Validation Metric Progression', fontsize=12, fontweight='bold')\n",
    "plt.xlabel('Epoch')\n",
    "plt.ylabel('Score')\n",
    "plt.grid(True, linestyle=':', alpha=0.5)\n",
    "plt.legend()\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Test Set Inference & Submission Generation (`submission.csv`)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "from src.inference import generate_submission\n",
    "\n",
    "sub_path = generate_submission(best_checkpoint, output_csv_path=\"submission.csv\", batch_size=32, device_str=str(device))\n",
    "print(f\"✓ Final Submission CSV Generated: {sub_path}\")"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

out_nb_path = r'c:\Users\hp\Desktop\OCR-chall\CRNN.ipynb'
with open(out_nb_path, 'w', encoding='utf-8') as f:
    json.dump(notebook_content, f, indent=1)

print(f"Jupyter Notebook successfully updated at: {out_nb_path}")
